Goldgym/Goldgym/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler400, handler403, handler404, handler500
from main import views

handler400 = 'main.views.error_400'
handler403 = 'main.views.error_403'
handler404 = 'main.views.error_404'
handler500 = 'main.views.error_500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('users.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('calculator/', include('calculator.urls', namespace='calculator')),
    path('', include('main.urls', namespace='main')),
    path('400/', views.error_400, kwargs={'exception': Exception('Bad Request')}),
    path('403/', views.error_403, kwargs={'exception': Exception('Permission Denied')}),
    path('404/', views.error_404, kwargs={'exception': Exception('Not Found')}),
    path('500/', views.error_500),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Goldgym/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
]

Goldgym/main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.popular_list, name='popular_list'),
    path('shop/', views.product_list, name='product_list'),
    path('shop/<slug:slug>/', views.product_detail, name='product_detail'),
    path('shop/category/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('', include('google_maps.urls')),
]

Goldgym/users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

Goldgym/main/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=20,
                            unique=True)
    slug = models.SlugField(max_length=20,
                            unique=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse("main:product_list_by_category",
                       args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    discount = models.DecimalField(default=0.00, max_digits=4,
                                   decimal_places=2)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product_detail',
                       args=[self.slug])

    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)
        return self.price


class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='images',
                                on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    def __str__(self):
        return f'{self.product.name} - {self.image.name}'

Goldgym/main/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from .models import Product, Category
from cart.forms import CartAddProductForm
from django.shortcuts import render

def popular_list(request):
    products = Product.objects.filter(available=True)[:3]
    return render(request,
                  'main/index/index.html',
                  {
                      'products': products,
                      'is_index_page': True
                   })


def product_detail(request, slug):
    product = get_object_or_404(Product,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm
    return render(request,
                  'main/product/detail.html',
                  {
                      'product': product,
                      'cart_product_form': cart_product_form,
                      'is_index_page': False
                   })


def product_list(request, category_slug=None):
    page = request.GET.get('page', 1)
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    paginator = Paginator(products, 10)
    current_page = paginator.page(int(page))
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        paginator = Paginator(products.filter(category=category), 10)
        current_page = paginator.page(int(page))
    return render(request,
                  'main/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': current_page,
                   'slug_url': category_slug,
                   'is_index_page': False
                   })


def error_400(request, exception):
    return render(request, 'errors/400.html', status=400)


def error_403(request, exception):
    return render(request, 'errors/403.html', status=403)


def error_404(request, exception):
    return render(request, 'errors/404.html', status=404)


def error_500(request):
    return render(request, 'errors/500.html', status=500)

Goldgym/main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>

    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!--  bootstrap   -->
    <link rel="stylesheet" href=" {% static 'bootstrap/css/bootstrap.min.css' %}">
    <!--    css   -->
<<<<<<< HEAD
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
  </head>
  <body>
    <header class="header sticky-top">
<<<<<<< HEAD
        <div class="header-container d-flex">
            <navbar class="header-nav pt-4">
                <ul class= "header-list d-flex">
                    <li>
<<<<<<< HEAD
                        <a href="/" class="nav-a m-3">Home</a>
=======
                        <a href="/calculator" class="nav-item">Calculator</a>
>>>>>>> 45420c5 (Created app calculator to calculate daily kcal (added new styles for calculator and result))
                    </li>
                    <li>
                        <a href="/shop" class="nav-a m-3">Shop</a>
                    </li>
<<<<<<< HEAD
=======
                    <li>
                        <a href="/gyms" class="nav-item">Map</a>
                    </li>
>>>>>>> 43d57e6 (Add google_maps(for searching gyms))
                </ul>
            </navbar>
            <div class="header-logo">
                <a href="/"><img src="{% static 'img/logo.png' %}" alt="" class="heavy-logo"></a>
            </div>
            <div class="header-profile pt-2">
<<<<<<< HEAD
                <a href="{% url 'cart:cart_detail'%}"><img src="{% static 'img/corth.png' %}" class="corth" alt=""></a>
                <a href="{% url "users:login" %}" class="m-2">LOGIN</a>
                <p class="cart-quantity">
                    {% with cart_quantity=cart|length %}
                        {% if cart_quantity > 0 %}
                            {{ cart_quantity }}
                        {% else %}
                            0
                        {% endif %}
                    {% endwith %}
                </p>
=======
                <div class="corth">
                    <a href="{% url 'cart:cart_detail'%}">
                        <img src="{% static 'img/corth.png' %}" class="cart-icon" alt="">
                    </a>
                    <p class="cart-quantity">
                        {% with cart_quantity=cart|length %}
                            {% if cart_quantity > 0 %}
                                {{ cart_quantity }}
                            {% else %}
                                0
                            {% endif %}
                        {% endwith %}
                    </p>
                </div>
                {% if user.is_authenticated %}
                    <a href="{% url "users:profile" %}" class="m-4">PROFILE</a>
                {% else %}
                    <a href="{% url "users:login" %}" class="m-2">LOGIN</a>
                {% endif %}
>>>>>>> a47ffd9 (fixing styles and fixin some mistakes in files)
            </div>
=======
      <div class="header-container">
        <div class="header-logo">
          <a href="/"
            ><img
              src="{% static 'img/logo.png' %}"
              alt="Gold's Gym"
              class="heavy-logo"
          /></a>
>>>>>>> 4e23637 (Started adapting styles for different screen resolutions)
=======
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/shop.css' %}">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    <link rel="stylesheet" href="{% static 'css/order.css' %}">
    <link rel="stylesheet" href="{% static 'css/payment.css' %}">
    <link rel="stylesheet" href="{% static 'css/calculator.css' %}">
    <link rel="stylesheet" href="{% static 'css/map.css' %}">
</head>
<body>
<div class="wrapper">
     <header class="header sticky-top">
        <div class="header-container">
            <div class="header-logo">
                <a href="/"><img src="{% static 'img/logo.png' %}" alt="Gold's Gym" class="heavy-logo"></a>
            </div>

            <button class="burger-menu d-lg-none" aria-label="Toggle navigation">
                <span class="burger-line"></span>
                <span class="burger-line"></span>
                <span class="burger-line"></span>
            </button>


            <nav class="header-nav">
                <ul class="header-list">
                    <li><a href="/calculator" class="nav-item">Calculator</a></li>
                    <li><a href="/shop" class="nav-item">Shop</a></li>
                    <li><a href="/gyms" class="nav-item">Map</a></li>
                </ul>
            </nav>

            <div class="header-profile">
                <div class="corth">
                    <a href="{% url 'cart:cart_detail'%}" aria-label="Cart">
                        <img src="{% static 'img/corth.png' %}" class="cart-icon" alt="Cart">
                        <span class="cart-quantity">
                            {% with cart_quantity=cart|length %}
                                {% if cart_quantity > 0 %}
                                    {{ cart_quantity }}
                                {% else %}
                                    0
                                {% endif %}
                            {% endwith %}
                        </span>
                    </a>
                </div>
                {% if user.is_authenticated %}
                    <a href="{% url 'users:profile' %}" class="btn-profile">PROFILE</a>
                {% else %}
                    <a href="{% url 'users:login' %}" class="btn-login">LOGIN</a>
                {% endif %}
            </div>
>>>>>>> ef65a6f (Split the file base.css into several files, and rewrote them html files for new styles such as: detail, index, list, create, process, login, registration)
        </div>
    </header>
    <div class="container">
    {% block content %}
    {% endblock content %}
    </div>

    <footer class="footer {% if not is_index_page %}footer-spaced{% endif %}">
        <div class="d-flex justify-content-between align-items-start mb-1">
            <h2 class="footer-title mb-0">STRONGER STARTS HERE</h2>
            <div class="social-icons">
                <div class="social-icon"><img src="{% static 'img/instagram.png' %}"  href="#" alt=""></div>
                <div class="social-icon"><img src="{% static 'img/facebook.png' %}"  href="#" alt=""></div>
                <div class="social-icon"><img src="{% static 'img/x.png' %}"  href="#" alt=""></div>
                <div class="social-icon"><img src="{% static 'img/youtube.png' %}"  href="#" alt=""></div>
            </div>
        </div>

        <div class="footer-nav">
            <a href="#" class="footer-link">Find a Gym</a>
            <a href="#" class="footer-link">Shop</a>
            <a href="#" class="footer-link">Calculator</a>
        </div>

        <div class="footer-divider"></div>

        <div class="footer-links">
            <a href="#" class="footer-link" >own a gold's gym franchise</a>
            <a href="#" class="footer-link" >careers</a>
            <a href="#" class="footer-link" >diversity, equity & inclusion</a>
            <a href="#" class="footer-link" >Privacy Notice</a>
            <a href="#" class="footer-link" >State Privacy Notice</a>
            <a href="#" class="footer-link" >Terms & Conditions</a>
        </div>

        <p class="footer-copyright">© 2024 GOLD'S GYM – ALL RIGHTS RESERVED</p>
    </footer>
</div>


    <!--  js bootstrap  -->
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
            document.addEventListener('DOMContentLoaded', function() {
                const burgerMenu = document.querySelector('.burger-menu');
                const headerNav = document.querySelector('.header-nav');

                burgerMenu.addEventListener('click', function() {
                    this.classList.toggle('active');
                    headerNav.classList.toggle('active');
                });

                document.querySelectorAll('.header-nav a').forEach(link => {
                    link.addEventListener('click', function() {
                        burgerMenu.classList.remove('active');
                        headerNav.classList.remove('active');
                    });
                });
            });
        </script>
</body>
</html>